### ISSUE TITLE
Android客户端解密错误

### ISSUE THREAD

**Issue by huhuang03** [NEYouFan/ht-candywebcache-demo-server#1]
下载完Zip包之后，解密错误。log如下：

``` java
10-24 02:19:56.960 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err: javax.crypto.BadPaddingException: pad block corrupted
10-24 02:19:56.960 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at com.android.org.bouncycastle.jce.provider.JCEBlockCipher.engineDoFinal(JCEBlockCipher.java:701)
10-24 02:19:56.960 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at javax.crypto.Cipher.doFinal(Cipher.java:1111)
10-24 02:19:56.960 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at com.netease.hearttouch.candywebcache.cachemanager.DESUtils.decrypt(DESUtils.java:98)
10-24 02:19:56.960 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at com.netease.hearttouch.candywebcache.cachemanager.EnDecryptionUtils.decode(EnDecryptionUtils.java:23)
10-24 02:19:56.960 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at com.netease.hearttouch.candywebcache.cachemanager.CacheManager$PatchApplyer.applyPatch(CacheManager.java:601)
10-24 02:19:56.960 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at com.netease.hearttouch.candywebcache.cachemanager.CacheManager.applyPatch(CacheManager.java:679)
10-24 02:19:56.960 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at com.netease.hearttouch.candywebcache.CandyWebCache$PatchTask.doInBackground(CandyWebCache.java:467)
10-24 02:19:56.960 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at com.netease.hearttouch.candywebcache.CandyWebCache$PatchTask.doInBackground(CandyWebCache.java:453)
10-24 02:19:56.960 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at java.lang.Thread.run(Thread.java:856)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err: java.lang.NullPointerException
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at java.lang.String.<init>(String.java:238)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at com.netease.hearttouch.candywebcache.cachemanager.EnDecryptionUtils.decode(EnDecryptionUtils.java:23)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at com.netease.hearttouch.candywebcache.cachemanager.CacheManager$PatchApplyer.applyPatch(CacheManager.java:601)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at com.netease.hearttouch.candywebcache.cachemanager.CacheManager.applyPatch(CacheManager.java:679)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at com.netease.hearttouch.candywebcache.CandyWebCache$PatchTask.doInBackground(CandyWebCache.java:467)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at com.netease.hearttouch.candywebcache.CandyWebCache$PatchTask.doInBackground(CandyWebCache.java:453)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
10-24 02:19:56.964 2124-2194/com.netease.hearttouch.candywebcache.demoapp W/System.err:     at java.lang.Thread.run(Thread.java:856)
```

上传没有改，如下：

``` python
def create_md5(diff_file_name):
    """                                                                                                                                                                           
        加密处理的                                                                                                                                                                
        :param diff_file_name:                                                                                                                                                    
        :return:                                                                                                                                                                  
        """

    md5_value = hashlib.md5(diff_file_name.encode()).hexdigest()
    des_obj = DES.new("12344321")
    output_value = base64.b64encode(des_obj.encrypt(md5_value))


    return str(output_value, encoding="utf-8")
```

安卓端配置也是demo中的没有改：

``` java
   private static final String PASSWORD = "12344321";
    public static String encode(String dataSrc) {
        String encryptedStr = null;
        try {
            encryptedStr = Base64.encode(DESUtils.encrypt(dataSrc.getBytes(),  PASSWORD.getBytes()));
        } catch (UnsupportedEncodingException e) {
        }
        return encryptedStr;
    }

    public static String decode(String encryptedStr) {
        String decryptedStr = "";
        try {
            byte[] decryptedData = Base64.decode(encryptedStr);
            decryptedStr = new String(DESUtils.decrypt(decryptedData, PASSWORD.getBytes()), "UTF-8");
        } catch (UnsupportedEncodingException e) {
        } catch (Exception e) {
            e.printStackTrace();
        }
        return decryptedStr;
    }
```

请问是什么问题呢？

**Comment by hanpfei** [comment]
麻烦你把 encryptedStr 这个字符串贴一下

**Comment by huhuang03** [comment]
```
    public static String decode(String encryptedStr) {
        Log.i("tonghu", "EnDecryptionUtils1 decode: " + encryptedStr);
        String decryptedStr = "";
        try {
            byte[] decryptedData = Base64.decode(encryptedStr);
            decryptedStr = new String(DESUtils.decrypt(decryptedData, PASSWORD.getBytes()), "UTF-8");
        } catch (UnsupportedEncodingException e) {
        } catch (Exception e) {
            e.printStackTrace();
        }
        return decryptedStr;
    }
```

打印如下：
`I/tonghu  (29744): EnDecryptionUtils1 decode: yJRUYH2ve4TAJTaFT7puRQpfLvA/lACPFiS9vadCqu0=`

**Comment by hanpfei** [comment]
再把服务器产生的字符串贴一下？

感觉像是 create_md5(diff_file_name) 产生的md5字符串被截断了。

**Comment by hanpfei** [comment]
create_md5(diff_file_name) 产生的md5字符串是不是被保存了数据库，然后客户端请求的时候，从数据库拿的字符串？
数据库对相应的字段的长度的设置是多少？

**Comment by huhuang03** [comment]
``` python
def create_md5(diff_file_name):
    """                                                                                                                                                                           
        加密处理的                                                                                                                                                                
        :param diff_file_name:                                                                                                                                                    
        :return:                                                                                                                                                                  
        """

    md5_value = hashlib.md5(diff_file_name.encode()).hexdigest()
    des_obj = DES.new("12344321")
    output_value = base64.b64encode(des_obj.encrypt(md5_value))


    rst = str(output_value, encoding="utf-8")
    print("source str: " + diff_file_name + ", rst: " + rst)
    return rst
```

执行上传`python3 upload.py`的时候log如下：

```
source str: http://192.168.32.102:8000/packages/static.zip, rst: yJRUYH2ve4TAJTaFT7puRQpfLvA/lACPFiS9vadCqu0=
{"code": 200, "errMsg": "ok", "data": {"insert_cnt": 1}}
```

sqlite db的建表约束`.schema versionInfo`：

``` sqlite
CREATE TABLE versionInfo(
                  id integer primary key autoincrement unique not null,
                  appID varchar(128),
                  appVersion varchar(128),
                  resID varchar(128),
                  resVersion varchar(128),
                  diffUrl varchar(128),
                  diffMd5 varchar(128),
                  fullUrl varchar(128),
                  fullMd5 varchar(128),
                  domain varchar(256)
                );
```

查询结果`select * from versionInfo where appID='hello';`:
`6|hello|1.0.0|hello|20160703|||http://192.168.32.102:8000/packages/static.zip|yJRUYH2ve4TAJTaFT7puRQpfLvA/lACPFiS9vadCqu0=|192.168.32.10`

**Comment by hanpfei** [comment]
python 的 demo服务器DES加密的参数和客户端Java DES解密的参数有点不匹配，python demo server更新过了，可以拉下来试一下。

**Comment by huhuang03** [comment]
好的，谢谢！
